Member.create(name:"すぎうら", account: "Izumi_Konata", achievement: "全国ベスト8 2回")
Member.create(name:"ぷく", account: "kenokohe", achievement: "現役奨励会三段")
Member.create(name:"ほっしー", account: "Aleister_Crowley", achievement: "元奨、全国優勝2回、プロ棋戦出場経験有")
Member.create(name:"あつと", account: "endo_sakura", achievement: "現役奨励会5級")
Member.create(name:"しゅん", account: "Ohashi Keika", achievement: "現役奨励会三段")
Member.create(name:"しゅうまい", account: "shushu2016", achievement: "現役奨励会員")
Member.create(name:"TK", account: "chaos chaos", achievement: "全国準優勝1回、ベスト4 1回")
Member.create(name:"こいし", account: "Kirakrbosi", achievement: "元奨、全国準優勝")
Member.create(name:"れおす", account: "praimary", achievement: "全国優勝3回、プロ公式戦16局")
Member.create(name:"カイト", account: "kondo_2sei", achievement: "全国優勝２回")
Member.create(name:"へいや", account: "KH1995", achievement: "全国準優勝１回")
Member.create(name:"２６銀", account: "Chono Hisayosi", achievement: "全国優勝２回、")
Member.create(name:"きふわるべ", account: "Kifuwarube", achievement: "天才きふわらべ氏によって生み出されたきふわるべ")

Result.create(member_id:1, op_id:1)
Result.create(member_id:1, op_id:2)
Result.create(member_id:1, op_id:3)
Result.create(member_id:1, op_id:4)
Result.create(member_id:1, op_id:5)
Result.create(member_id:1, op_id:6)
Result.create(member_id:1, op_id:7)
Result.create(member_id:1, op_id:8)
Result.create(member_id:1, op_id:9)
Result.create(member_id:1, op_id:10)
Result.create(member_id:1, op_id:11)
Result.create(member_id:1, op_id:12)
Result.create(member_id:1, op_id:13)

Result.create(member_id:2, op_id:1)
Result.create(member_id:2, op_id:2)
Result.create(member_id:2, op_id:3)
Result.create(member_id:2, op_id:4)
Result.create(member_id:2, op_id:5)
Result.create(member_id:2, op_id:6)
Result.create(member_id:2, op_id:7)
Result.create(member_id:2, op_id:8)
Result.create(member_id:2, op_id:9)
Result.create(member_id:2, op_id:10)
Result.create(member_id:2, op_id:11)
Result.create(member_id:2, op_id:12)
Result.create(member_id:2, op_id:13)

Result.create(member_id:3, op_id:1)
Result.create(member_id:3, op_id:2)
Result.create(member_id:3, op_id:3)
Result.create(member_id:3, op_id:4)
Result.create(member_id:3, op_id:5)
Result.create(member_id:3, op_id:6)
Result.create(member_id:3, op_id:7)
Result.create(member_id:3, op_id:8)
Result.create(member_id:3, op_id:9)
Result.create(member_id:3, op_id:10)
Result.create(member_id:3, op_id:11)
Result.create(member_id:3, op_id:12)
Result.create(member_id:3, op_id:13)

Result.create(member_id:4, op_id:1)
Result.create(member_id:4, op_id:2)
Result.create(member_id:4, op_id:3)
Result.create(member_id:4, op_id:4)
Result.create(member_id:4, op_id:5)
Result.create(member_id:4, op_id:6)
Result.create(member_id:4, op_id:7)
Result.create(member_id:4, op_id:8)
Result.create(member_id:4, op_id:9)
Result.create(member_id:4, op_id:10)
Result.create(member_id:4, op_id:11)
Result.create(member_id:4, op_id:12)
Result.create(member_id:4, op_id:13)

Result.create(member_id:5, op_id:1)
Result.create(member_id:5, op_id:2)
Result.create(member_id:5, op_id:3)
Result.create(member_id:5, op_id:4)
Result.create(member_id:5, op_id:5)
Result.create(member_id:5, op_id:6)
Result.create(member_id:5, op_id:7)
Result.create(member_id:5, op_id:8)
Result.create(member_id:5, op_id:9)
Result.create(member_id:5, op_id:10)
Result.create(member_id:5, op_id:11)
Result.create(member_id:5, op_id:12)
Result.create(member_id:5, op_id:13)

Result.create(member_id:6, op_id:1)
Result.create(member_id:6, op_id:2)
Result.create(member_id:6, op_id:3)
Result.create(member_id:6, op_id:4)
Result.create(member_id:6, op_id:5)
Result.create(member_id:6, op_id:6)
Result.create(member_id:6, op_id:7)
Result.create(member_id:6, op_id:8)
Result.create(member_id:6, op_id:9)
Result.create(member_id:6, op_id:10)
Result.create(member_id:6, op_id:11)
Result.create(member_id:6, op_id:12)
Result.create(member_id:6, op_id:13)

Result.create(member_id:7, op_id:1)
Result.create(member_id:7, op_id:2)
Result.create(member_id:7, op_id:3)
Result.create(member_id:7, op_id:4)
Result.create(member_id:7, op_id:5)
Result.create(member_id:7, op_id:6)
Result.create(member_id:7, op_id:7)
Result.create(member_id:7, op_id:8)
Result.create(member_id:7, op_id:9)
Result.create(member_id:7, op_id:10)
Result.create(member_id:7, op_id:11)
Result.create(member_id:7, op_id:12)
Result.create(member_id:7, op_id:13)

Result.create(member_id:8, op_id:1)
Result.create(member_id:8, op_id:2)
Result.create(member_id:8, op_id:3)
Result.create(member_id:8, op_id:4)
Result.create(member_id:8, op_id:5)
Result.create(member_id:8, op_id:6)
Result.create(member_id:8, op_id:7)
Result.create(member_id:8, op_id:8)
Result.create(member_id:8, op_id:9)
Result.create(member_id:8, op_id:10)
Result.create(member_id:8, op_id:11)
Result.create(member_id:8, op_id:12)
Result.create(member_id:8, op_id:13)

Result.create(member_id:9, op_id:1)
Result.create(member_id:9, op_id:2)
Result.create(member_id:9, op_id:3)
Result.create(member_id:9, op_id:4)
Result.create(member_id:9, op_id:5)
Result.create(member_id:9, op_id:6)
Result.create(member_id:9, op_id:7)
Result.create(member_id:9, op_id:8)
Result.create(member_id:9, op_id:9)
Result.create(member_id:9, op_id:10)
Result.create(member_id:9, op_id:11)
Result.create(member_id:9, op_id:12)
Result.create(member_id:9, op_id:13)

Result.create(member_id:10, op_id:1)
Result.create(member_id:10, op_id:2)
Result.create(member_id:10, op_id:3)
Result.create(member_id:10, op_id:4)
Result.create(member_id:10, op_id:5)
Result.create(member_id:10, op_id:6)
Result.create(member_id:10, op_id:7)
Result.create(member_id:10, op_id:8)
Result.create(member_id:10, op_id:9)
Result.create(member_id:10, op_id:10)
Result.create(member_id:10, op_id:11)
Result.create(member_id:10, op_id:12)
Result.create(member_id:10, op_id:13)

Result.create(member_id:11, op_id:1)
Result.create(member_id:11, op_id:2)
Result.create(member_id:11, op_id:3)
Result.create(member_id:11, op_id:4)
Result.create(member_id:11, op_id:5)
Result.create(member_id:11, op_id:6)
Result.create(member_id:11, op_id:7)
Result.create(member_id:11, op_id:8)
Result.create(member_id:11, op_id:9)
Result.create(member_id:11, op_id:10)
Result.create(member_id:11, op_id:11)
Result.create(member_id:11, op_id:12)
Result.create(member_id:11, op_id:13)

Result.create(member_id:12, op_id:1)
Result.create(member_id:12, op_id:2)
Result.create(member_id:12, op_id:3)
Result.create(member_id:12, op_id:4)
Result.create(member_id:12, op_id:5)
Result.create(member_id:12, op_id:6)
Result.create(member_id:12, op_id:7)
Result.create(member_id:12, op_id:8)
Result.create(member_id:12, op_id:9)
Result.create(member_id:12, op_id:10)
Result.create(member_id:12, op_id:11)
Result.create(member_id:12, op_id:12)
Result.create(member_id:12, op_id:13)

Result.create(member_id:13, op_id:1)
Result.create(member_id:13, op_id:2)
Result.create(member_id:13, op_id:3)
Result.create(member_id:13, op_id:4)
Result.create(member_id:13, op_id:5)
Result.create(member_id:13, op_id:6)
Result.create(member_id:13, op_id:7)
Result.create(member_id:13, op_id:8)
Result.create(member_id:13, op_id:9)
Result.create(member_id:13, op_id:10)
Result.create(member_id:13, op_id:11)
Result.create(member_id:13, op_id:12)
Result.create(member_id:13, op_id:13)